package tdd.huffman;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import static org.assertj.core.api.Assertions.assertThat;

class HuffmanCompressionIT {

    private final String TEST_DATA = "-, sed ut hoc iudicaremus, non esse in iis partem maximam positam beate aut secus vivendi. Si est nihil in eo, quod perficiendum est, praeter motum ingenii quendam, id est rationem, necesse est huic ultimum esse virtute agere; Nam nec vir bonus ac iustus haberi debet qui, ne malum habeat, abstinet se ab iniuria. Tum, Quintus et Pomponius cum idem se velle dixissent, Piso exorsus est. Restincta enim sitis stabilitatem voluptatis habet, inquit, illa autem voluptas ipsius restinctionis in motu est. Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Beatus sibi videtur esse moriens. Bonum incolumis acies: misera caecitas. Re mihi non aeque satisfacit, et quidem locis pluribus. Vos autem cum perspicuis dubia debeatis illustrare, dubiis perspicua conamini tollere. Sed haec ab Antiocho, familiari nostro, dicuntur multo melius et fortius, quam a Stasea dicebantur." +
            "Ad corpus diceres pertinere-, sed ea, quae dixi, ad corpusne refers? Facile est hoc cernere in primis puerorum aetatulis. Sunt autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos diligant. Nam aliquando posse recte fieri dicunt nulla expectata nec quaesita voluptate. Et hi quidem ita non sola virtute finem bonorum contineri putant, ut rebus tamen omnibus virtutem anteponant; Aliud est enim poëtarum more verba fundere, aliud ea, quae dicas, ratione et arte distinguere. Ego quoque, inquit, didicerim libentius si quid attuleris, quam te reprehenderim. Sunt enim prima elementa naturae, quibus auctis vírtutis quasi germen efficitur. Quarum ambarum rerum cum medicinam pollicetur, luxuriae licentiam pollicetur. Quam ob rem utique idem faciunt, ut si laevam partem neglegerent, dexteram tuerentur, aut ipsius animi, ut fecit Erillus, cognitionem amplexarentur, actionem relinquerent. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet;" +
            "At cum tuis cum disseras, multa sunt audienda etiam de obscenis voluptatibus, de quibus ab Epicuro saepissime dicitur. Neque solum ea communia, verum etiam paria esse dixerunt. Inquit, an parum disserui non verbis Stoicos a Peripateticis, sed universa re et tota sententia dissidere? Omnia contraria, quos etiam insanos esse vultis. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Cum enim fertur quasi torrens oratio, quamvis multa cuiusque modi rapiat, nihil tamen teneas, nihil apprehendas, nusquam orationem rapidam coerceas. Si ista mala sunt, in quae potest incidere sapiens, sapientem esse non esse ad beate vivendum satis. Ego vero volo in virtute vim esse quam maximam;" +
            "At enim hic etiam dolore. Longum est enim ad omnia respondere, quae a te dicta sunt. Ut aliquid scire se gaudeant? Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri. E quo efficitur, non ut nos non intellegamus quae vis sit istius verbi, sed ut ille suo more loquatur, nostrum neglegat. Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Neque enim civitas in seditione beata esse potest nec in discordia dominorum domus; Ergo infelix una molestia, fellx rursus, cum is ipse anulus in praecordiis piscis inventus est? Sed tamen enitar et, si minus multa mihi occurrent, non fugiam ista popularia." +
            "At iam decimum annum in spelunca iacet. Numquam audivi in Epicuri schola Lycurgum, Solonem, Miltiadem, Themistoclem, Epaminondam nominari, qui in ore sunt ceterorum omnium philosophorum. Plane idem, inquit, et maxima quidem, qua fieri nulla maior potest. Octavium, Marci filium, familiarem meum, confici vidi, nec vero semel nec ad breve tempus, sed et saepe et plane diu. Multa sunt dicta ab antiquis de contemnendis ac despiciendis rebus humanis; Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta? Deinde concludebas summum malum esse dolorem, summum bonum voluptatem! Lucius Thorius Balbus fuit, Lanuvinus, quem meminisse tu non potes. Huic ego, si negaret quicquam interesse ad beate vivendum quali uteretur victu, concederem, laudarem etiam; Sed potestne rerum maior esse dissensio? Hi curatione adhibita levantur in dies, valet alter plus cotidie, alter videt. Haec non erant eius, qui innumerabilis mundos infinitasque regiones, quarum nulla esset ora, nulla extremitas, mente peragravisset. Si ad corpus pertinentibus, rationes tuas te video compensare cum istis doloribus, non memoriam corpore perceptarum voluptatum; Haec non erant eius, qui innumerabilis mundos infinitasque regiones, quarum nulla esset ora, nulla extremitas, mente peragravisset." +
            "At ille pellit, qui permulcet sensum voluptate. Stoici autem, quod finem bonorum in una virtute ponunt, similes sunt illorum; Satisne ergo pudori consulat, si quis sine teste libidini pareat? Prodest, inquit, mihi eo esse animo. Quia nec honesto quic quam honestius nec turpi turpius. Hoc est non modo cor non habere, sed ne palatum quidem. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Introduci enim virtus nullo modo potest, nisi omnia, quae leget quaeque reiciet, unam referentur ad summam." +
            "At tu eadem ista dic in iudicio aut, si coronam times, dic in senatu. Sic enim maiores nostri labores non fugiendos tristissimo tamen verbo aerumnas etiam in deo nominaverunt. Cum autem progrediens confirmatur animus, agnoscit ille quidem naturae vim, sed ita, ut progredi possit longius, per se sit tantum inchoata. Neutrum vero, inquit ille. Hoc autem loco tantum explicemus haec honesta, quae dico, praeterquam quod nosmet ipsos diligamus, praeterea suapte natura per se esse expetenda. Istic sum, inquit. Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Vobis autem, quibus nihil est aliud propositum nisi rectum atque honestum, unde officii, unde agendi principlum nascatur non reperietis. Vide ne ista sint Manliana vestra aut maiora etiam, si imperes quod facere non possim. Isto modo, ne si avia quidem eius nata non esset. In omni enim arte vel studio vel quavis scientia vel in ipsa virtute optimum quidque rarissimum est. Non igitur potestis voluptate omnia dirigentes aut tueri aut retinere virtutem. Verum tamen cum de rebus grandioribus dicas, ipsae res verba rapiunt;" +
            "Atque ab his initiis profecti omnium virtutum et originem et progressionem persecuti sunt. Nec vero pietas adversus deos nec quanta iis gratia debeatur sine explicatione naturae intellegi potest. Expressa vero in iis aetatibus, quae iam confirmatae sunt. Te enim iudicem aequum puto, modo quae dicat ille bene noris. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Dicet pro me ipsa virtus nec dubitabit isti vestro beato M. Istic sum, inquit. Quid, cum fictas fabulas, e quibus utilitas nulla elici potest, cum voluptate legimus? Et hi quidem ita non sola virtute finem bonorum contineri putant, ut rebus tamen omnibus virtutem anteponant; Eam si varietatem diceres, intellegerem, ut etiam non dicente te intellego; Id et fieri posse et saepe esse factum et ad voluptates percipiendas maxime pertinere." +
            "Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Piso, familiaris noster, et alia multa et hoc loco Stoicos irridebat: Quid enim? Egone non intellego, quid sit don Graece, Latine voluptas? Negat enim summo bono afferre incrementum diem. Huc et illuc, Torquate, vos versetis licet, nihil in hac praeclara epistula scriptum ab Epicuro congruens et conveniens decretis eius reperietis. Alterum autem genus est magnarum verarumque virtutum, quas appellamus voluntarias, ut prudentiam, temperantiam, fortitudinem, iustitiam et reliquas eiusdem generis. Quae etsi mihi nullo modo probantur, tamen Democritum laudatum a ceteris ab hoc, qui eum unum secutus esset, nollem vituperatum. Cur igitur, inquam, res tam dissimiles eodem nomine appellas? Tum Piso: Atqui, Cicero, inquit, ista studia, si ad imitandos summos viros spectant, ingeniosorum sunt; Quare obscurentur etiam haec, quae secundum naturam esse dicimus, in vita beata;" +
            "Atque ita re simpliciter primo collocata reliqua subtilius persequentes corporis bona facilem quandam rationem habere censebant; Graecum enim hunc versum nostis omnes-: Suavis laborum est praeteritorum memoria. Semper enim ex eo, quod maximas partes continet latissimeque funditur, tota res appellatur. Mihi quidem Homerus huius modi quiddam vidisse videatur in iis, quae de Sirenum cantibus finxerit. Hoc simile tandem est? Si enim non fuit eorum iudicii, nihilo magis hoc non addito illud est iudicatum-. Nam nec vir bonus ac iustus haberi debet qui, ne malum habeat, abstinet se ab iniuria." +
            "Atque omnia quidem scire, cuiuscumque modi sint, cupere curiosorum, duci vero maiorum rerum contemplatione ad cupiditatem scientiae summorum virorum est putandum. Collige omnia, quae soletis: Praesidium amicorum. Intrandum est igitur in rerum naturam et penitus quid ea postulet pervidendum; Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus. Ut necesse sit omnium rerum, quae natura vigeant, similem esse finem, non eundem. Quid enim necesse est, tamquam meretricem in matronarum coetum, sic voluptatem in virtutum concilium adducere? Non enim, si omnia non sequebatur, idcirco non erat ortus illinc. Peccata autem partim esse tolerabilia, partim nullo modo, propterea quod alia peccata plures, alia pauciores quasi numeros officii praeterirent. Nunc de hominis summo bono quaeritur; Quae hic rei publicae vulnera inponebat, eadem ille sanabat." +
            "Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Portenta haec esse dicit, neque ea ratione ullo modo posse vivi; Cognitio autem haec est una nostri, ut vim corporis animique norimus sequamurque eam vitam, quae rebus iis ipsis perfruatur. Sunt etiam turpitudines plurimae, quae, nisi honestas natura plurimum valeat, cur non cadant in sapientem non est facile defendere. Huic ego, si negaret quicquam interesse ad beate vivendum quali uteretur victu, concederem, laudarem etiam; Nam nec vir bonus ac iustus haberi debet qui, ne malum habeat, abstinet se ab iniuria. Perturbationes autem nulla naturae vi commoventur, omniaque ea sunt opiniones ac iudicia levitatis." +
            "Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Tanta vis admonitionis inest in locis; Cetera illa adhibebat, quibus demptis negat se Epicurus intellegere quid sit bonum. Pauca mutat vel plura sane; Se omnia, quae secundum naturam sint, b o n a appellare, quae autem contra, m a l a. Sic enim maiores nostri labores non fugiendos tristissimo tamen verbo aerumnas etiam in deo nominaverunt. An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? Habent enim et bene longam et satis litigiosam disputationem. Tecum optime, deinde etiam cum mediocri amico. Respondent extrema primis, media utrisque, omnia omnibus." +
            "Aut, Pylades cum sis, dices te esse Orestem, ut moriare pro amico? Qui est in parvis malis. Amicitiae vero locus ubi esse potest aut quis amicus esse cuiquam, quem non ipsum amet propter ipsum? Si vero id etiam explanare velles apertiusque diceres nihil eum fecisse nisi voluptatis causa, quo modo eum tandem laturum fuisse existimas? Tollenda est atque extrahenda radicitus. Cum autem venissemus in Academiae non sine causa nobilitata spatia, solitudo erat ea, quam volueramus. Qui bonum omne in virtute ponit, is potest dicere perfici beatam vitam perfectione virtutis; Quid enim necesse est, tamquam meretricem in matronarum coetum, sic voluptatem in virtutum concilium adducere? Sed quid sentiat, non videtis. Ut enim consuetudo loquitur, id solum dicitur honestum, quod est populari fama gloriosum." +
            "Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Haec quo modo conveniant, non sane intellego. Non enim in selectione virtus ponenda erat, ut id ipsum, quod erat bonorum ultimum, aliud aliquid adquireret. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia; Nam et complectitur verbis, quod vult, et dicit plane, quod intellegam; Cuius similitudine perspecta in formarum specie ac dignitate transitum est ad honestatem dictorum atque factorum. Verum hoc loco sumo verbis his eandem certe vim voluptatis Epicurum nosse quam ceteros. Ex quo magnitudo quoque animi existebat, qua facile posset repugnari obsistique fortunae, quod maximae res essent in potestate sapientis. Miserum hominem! Si dolor summum malum est, dici aliter non potest." +
            "Cum autem negant ea quicquam ad beatam vitam pertinere, rursus naturam relinquunt. Cur ad reliquos Pythagoreos, Echecratem, Timaeum, Arionem, Locros, ut, cum Socratem expressisset, adiungeret Pythagoreorum disciplinam eaque, quae Socrates repudiabat, addisceret? Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio? Cuius similitudine perspecta in formarum specie ac dignitate transitum est ad honestatem dictorum atque factorum. Quarum cum una sit, qua mores conformari putantur, differo eam partem, quae quasi stirps ets huius quaestionis. Quod si ita est, sequitur id ipsum, quod te velle video, omnes semper beatos esse sapientes. Qui autem voluptate vitam effici beatam putabit, qui sibi is conveniet, si negabit voluptatem crescere longinquitate? Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri. Qui potest igitur habitare in beata vita summi mali metus?" +
            "Cum autem progrediens confirmatur animus, agnoscit ille quidem naturae vim, sed ita, ut progredi possit longius, per se sit tantum inchoata. Quod si ita se habeat, non possit beatam praestare vitam sapientia. Tum ille: Finem, inquit, interrogandi, si videtur, quod quidem ego a principio ita me malle dixeram hoc ipsum providens, dialecticas captiones. Deinde qui fit, ut ego nesciam, sciant omnes, quicumque Epicurei esse voluerunt? Nam illud quidem adduci vix possum, ut ea, quae senserit ille, tibi non vera videantur. Ea possunt paria non esse. Quodsi Graeci leguntur a Graecis isdem de rebus alia ratione compositis, quid est, cur nostri a nostris non legantur? Re mihi non aeque satisfacit, et quidem locis pluribus. Venit enim mihi Platonis in mentem, quem accepimus primum hic disputare solitum;" +
            "Cum id quoque, ut cupiebat, audivisset, evelli iussit eam, qua erat transfixus, hastam. Quare attendo te studiose et, quaecumque rebus iis, de quibus hic sermo est, nomina inponis, memoriae mando; Atqui haec patefactio quasi rerum opertarum, cum quid quidque sit aperitur, definitio est. Quod cum ille dixisset et satis disputatum videretur, in oppidum ad Pomponium perreximus omnes. Dic in quovis conventu te omnia facere, ne doleas. Sed audiamus ipsum: Compensabatur, inquit, tamen cum his omnibus animi laetitia, quam capiebam memoria rationum inventorumque nostrorum." +
            "Cum id quoque, ut cupiebat, audivisset, evelli iussit eam, qua erat transfixus, hastam. Roges enim Aristonem, bonane ei videantur haec: vacuitas doloris, divitiae, valitudo; Nam prius a se poterit quisque discedere quam appetitum earum rerum, quae sibi conducant, amittere. Quae adhuc, Cato, a te dicta sunt, eadem, inquam, dicere posses, si sequerere Pyrrhonem aut Aristonem. Quae similitudo in genere etiam humano apparet. Itaque quantum adiit periculum! ad honestatem enim illum omnem conatum suum referebat, non ad voluptatem. Sit ista in Graecorum levitate perversitas, qui maledictis insectantur eos, a quibus de veritate dissentiunt. Fortasse id optimum, sed ubi illud: Plus semper voluptatis?" +
            "Cur post Tarentum ad Archytam? Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Fieri, inquam, Triari, nullo pacto potest, ut non dicas, quid non probes eius, a quo dissentias. Habes undique expletam et perfectam, Torquate, formam honestatis, quae tota quattuor his virtutibus, quae a te quoque commemoratae sunt, continetur. Quis est tam dissimile homini. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. Legimus tamen Diogenem, Antipatrum, Mnesarchum, Panaetium, multos alios in primisque familiarem nostrum Posidonium. Ubi ut eam caperet aut quando? De malis autem et bonis ab iis animalibus, quae nondum depravata sint, ait optime iudicari. Ita enim vivunt quidam, ut eorum vita refellatur oratio. Homines optimi non intellegunt totam rationem everti, si ita res se habeat. Cur, nisi quod turpis oratio est?" +
            "Cynicorum autem rationem atque vitam alii cadere in sapientem dicunt, si qui eius modi forte casus inciderit, ut id faciendum sit, alii nullo modo. Scisse enim te quis coarguere possit? Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quid est, quod ab ea absolvi et perfici debeat? Facit enim ille duo seiuncta ultima bonorum, quae ut essent vera, coniungi debuerunt; Haec non erant eius, qui innumerabilis mundos infinitasque regiones, quarum nulla esset ora, nulla extremitas, mente peragravisset. Illa sunt similia: hebes acies est cuipiam oculorum, corpore alius senescit; Sapientem locupletat ipsa natura, cuius divitias Epicurus parabiles esse docuit. Quas enim kakaw Graeci appellant, vitia malo quam malitias nominare." +
            "Dat enim id nobis solitudo, quod si qui deus diceret, numquam putarem me in Academia tamquam philosophum disputaturum. Bonum incolumis acies: misera caecitas. Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Ex quo intellegitur officium medium quiddam esse, quod neque in bonis ponatur neque in contrariis. Non prorsus, inquit, omnisque, qui sine dolore sint, in voluptate, et ea quidem summa, esse dico. Itaque haec cum illis est dissensio, cum Peripateticis nulla sane. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Plane idem, inquit, et maxima quidem, qua fieri nulla maior potest." +
            "De malis autem et bonis ab iis animalibus, quae nondum depravata sint, ait optime iudicari. Num igitur utiliorem tibi hunc Triarium putas esse posse, quam si tua sint Puteolis granaria? Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Neque solum ea communia, verum etiam paria esse dixerunt. Respondent extrema primis, media utrisque, omnia omnibus. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Atque etiam valítudinem, vires, vacuitatem doloris non propter utilitatem solum, sed etiam ipsas propter se expetemus. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Ergo id est convenienter naturae vivere, a natura discedere. Quare attendo te studiose et, quaecumque rebus iis, de quibus hic sermo est, nomina inponis, memoriae mando;" +
            "Deinceps videndum est, quoniam satis apertum est sibi quemque natura esse carum, quae sit hominis natura. Ut proverbia non nulla veriora sint quam vestra dogmata. Omnia contraria, quos etiam insanos esse vultis. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Ego vero volo in virtute vim esse quam maximam; Quam multa vitiosa! summum enim bonum et malum vagiens puer utra voluptate diiudicabit, stante an movente? Quod enim testimonium maius quaerimus, quae honesta et recta sint, ipsa esse optabilia per sese, cum videamus tanta officia morientis? Nec vero umquam summum bonum assequi quisquam posset, si omnia illa, quae sunt extra, quamquam expetenda, summo bono continerentur." +
            "Deinde disputat, quod cuiusque generis animantium statui deceat extremum. Quid in isto egregio tuo officio et tanta fide-sic enim existimo-ad corpus refers? Sed finge non solum callidum eum, qui aliquid improbe faciat, verum etiam praepotentem, ut M. Cupit enim dícere nihil posse ad beatam vitam deesse sapienti. Vulgo enim dicitur: Iucundi acti labores, nec male Euripidesconcludam, si potero, Latine; Non est igitur voluptas bonum. Servari enim iustitia nisi a forti viro, nisi a sapiente non potest. Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Ergo, si semel tristior effectus est, hilara vita amissa est?" +
            "Deinde prima illa, quae in congressu solemus: Quid tu, inquit, huc? Ergo infelix una molestia, fellx rursus, cum is ipse anulus in praecordiis piscis inventus est? Si ista mala sunt, in quae potest incidere sapiens, sapientem esse non esse ad beate vivendum satis. Huc et illuc, Torquate, vos versetis licet, nihil in hac praeclara epistula scriptum ab Epicuro congruens et conveniens decretis eius reperietis. Nam cui proposito sit conservatio sui, necesse est huic partes quoque sui caras suo genere laudabiles. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Et nunc quidem quod eam tuetur, ut de vite potissimum loquar, est id extrinsecus; Quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est." +
            "Dicet pro me ipsa virtus nec dubitabit isti vestro beato M. Et non ex maxima parte de tota iudicabis? Vides igitur, si amicitiam sua caritate metiare, nihil esse praestantius, sin emolumento, summas familiaritates praediorum fructuosorum mercede superari. Mihi, inquam, qui te id ipsum rogavi? -delector enim, quamquam te non possum, ut ais, corrumpere, delector, inquam, et familia vestra et nomine. Ut in geometria, prima si dederis, danda sunt omnia. Eamne rationem igitur sequere, qua tecum ipse et cum tuis utare, profiteri et in medium proferre non audeas? Vitiosum est enim in dividendo partem in genere numerare. Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat." +
            "Dolere malum est: in crucem qui agitur, beatus esse non potest. Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Non potes ergo ista tueri, Torquate, mihi crede, si te ipse et tuas cogitationes et studia perspexeris; At hoc in eo M. Quid affers, cur Thorius, cur Caius Postumius, cur omnium horum magister, Orata, non iucundissime vixerit? Tecum optime, deinde etiam cum mediocri amico. At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Non quaeritur autem quid naturae tuae consentaneum sit, sed quid disciplinae. Quaero igitur, quo modo hae tantae commendationes a natura profectae subito a sapientia relictae sint. Stoici scilicet. Numquam hoc ita defendit Epicurus neque Metrodorus aut quisquam eorum, qui aut saperet aliquid aut ista didicisset. Non enim actionis aut officii ratio impellit ad ea, quae secundum naturam sunt, petenda, sed ab iis et appetitio et actio commovetur." +
            "Dolere malum est: in crucem qui agitur, beatus esse non potest. Nam cui proposito sit conservatio sui, necesse est huic partes quoque sui caras suo genere laudabiles. Videmus igitur ut conquiescere ne infantes quidem possint. Quod ea non occurrentia fingunt, vincunt Aristonem; Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. At iste non dolendi status non vocatur voluptas. Nam si quae sunt aliae, falsum est omnis animi voluptates esse e corporis societate. Cum audissem Antiochum, Brute, ut solebam, cum M. Quaesita enim virtus est, non quae relinqueret naturam, sed quae tueretur. Id quaeris, inquam, in quo, utrum respondero, verses te huc atque illuc necesse est." +
            "Dulce amarum, leve asperum, prope longe, stare movere, quadratum rotundum. Cuius ad naturam apta ratio vera illa et summa lex a philosophis dicitur. Nec lapathi suavitatem acupenseri Galloni Laelius anteponebat, sed suavitatem ipsam neglegebat; At ille pellit, qui permulcet sensum voluptate. Nec vero hoc oratione solum, sed multo magis vita et factis et moribus comprobavit. Utrum enim sit voluptas in iis rebus, quas primas secundum naturam esse diximus, necne sit ad id, quod agimus, nihil interest. Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosissimis." +
            "Duo Reges: constructio interrete. An me, inquis, tam amentem putas, ut apud imperitos isto modo loquar? Nullis enim partitionibus, nullis definitionibus utuntur ipsique dicunt ea se modo probare, quibus natura tacita adsentiatur. Quarum ambarum rerum cum medicinam pollicetur, luxuriae licentiam pollicetur. De maximma autem re eodem modo, divina mente atque natura mundum universum et eius maxima partis administrari. In eo autem voluptas omnium Latine loquentium more ponitur, cum percipitur ea, quae sensum aliquem moveat, iucunditas. Nihil minus, contraque illa hereditate dives ob eamque rem laetus. Quaeque de virtutibus dicta sunt, quem ad modum eae semper voluptatibus inhaererent, eadem de amicitia dicenda sunt. Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? An vero, inquit, quisquam potest probare, quod perceptfum, quod. Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio?" +
            "Eam tum adesse, cum dolor omnis absit; Ac ne plura complectar-sunt enim innumerabilia-, bene laudata virtus voluptatis aditus intercludat necesse est. Quo invento omnis ab eo quasi capite de summo bono et malo disputatio ducitur. Tum Lucius: Mihi vero ista valde probata sunt, quod item fratri puto. Nam si dicent ab illis has res esse tractatas, ne ipsos quidem Graecos est cur tam multos legant, quam legendi sunt. Nunc vero a primo quidem mirabiliter occulta natura est nec perspici nec cognosci potest. Quaeque de virtutibus dicta sunt, quem ad modum eae semper voluptatibus inhaererent, eadem de amicitia dicenda sunt. Quod eo liquidius faciet, si perspexerit rerum inter eas verborumne sit controversia. Tum Lucius: Mihi vero ista valde probata sunt, quod item fratri puto. Octavio fuit, cum illam severitatem in eo filio adhibuit, quem in adoptionem D. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; Hoc sic expositum dissimile est superiori." +
            "Eam tum adesse, cum dolor omnis absit; Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Et quidem iure fortasse, sed tamen non gravissimum est testimonium multitudinis. Nam illud quidem adduci vix possum, ut ea, quae senserit ille, tibi non vera videantur. Quae quidem sapientes sequuntur duce natura tamquam videntes; Quid enim est tam repugnans quam eundem dicere, quod honestum sit, solum id bonum esse, qui dicat appetitionem rerum ad vivendum accommodatarum natura profectam? Nec enim absolvi beata vita sapientis neque ad exitum perduci poterit, si prima quaeque bene ab eo consulta atque facta ipsius oblivione obruentur. Quam haec sunt contraria! hic si definire, si dividere didicisset, si loquendi vim, si denique consuetudinem verborum teneret, numquam in tantas salebras incidisset. Quid enim mihi potest esse optatius quam cum Catone, omnium virtutum auctore, de virtutibus disputare? Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus. Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Ita fit ut, quanta differentia est in principiis naturalibus, tanta sit in finibus bonorum malorumque dissimilitudo. De maximma autem re eodem modo, divina mente atque natura mundum universum et eius maxima partis administrari." +
            "Ego, quam ille praeponendam et magis eligendam, beatiorem hanc appello nec ullo minimo momento plus ei vitae tribuo quam Stoici. Et hanc quidem primam exigam a te operam, ut audias me quae a te dicta sunt refellentem. Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosissimis. Quodsi Graeci leguntur a Graecis isdem de rebus alia ratione compositis, quid est, cur nostri a nostris non legantur? Praetereo multos, in bis doctum hominem et suavem, Hieronymum, quem iam cur Peripateticum appellem nescio. Sed emolumenta communia esse dicuntur, recte autem facta et peccata non habentur communia. An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia? Nec enim absolvi beata vita sapientis neque ad exitum perduci poterit, si prima quaeque bene ab eo consulta atque facta ipsius oblivione obruentur. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Immo istud quidem, inquam, quo loco quidque, nisi iniquum postulo, arbitratu meo." +
            "Egone non intellego, quid sit don Graece, Latine voluptas? Quid in isto egregio tuo officio et tanta fide-sic enim existimo-ad corpus refers? Ergo in iis adolescentibus bonam spem esse dicemus et magnam indolem, quos suis commodis inservituros et quicquid ipsis expediat facturos arbitrabimur? Hoc autem loco tantum explicemus haec honesta, quae dico, praeterquam quod nosmet ipsos diligamus, praeterea suapte natura per se esse expetenda. Qui autem diffidet perpetuitati bonorum suorum, timeat necesse est, ne aliquando amissis illis sit miser. Aufert enim sensus actionemque tollit omnem." +
            "Ergo in bestiis erunt secreta e voluptate humanarum quaedam simulacra virtutum, in ipsis hominibus virtus nisi voluptatis causa nulla erit? Et si turpitudinem fugimus in statu et motu corporis, quid est cur pulchritudinem non sequamur? Facit enim ille duo seiuncta ultima bonorum, quae ut essent vera, coniungi debuerunt; Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Aufert enim sensus actionemque tollit omnem. Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Quae diligentissime contra Aristonem dicuntur a Chryippo. His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus." +
            "Ergo in eadem voluptate eum, qui alteri misceat mulsum ipse non sitiens, et eum, qui illud sitiens bibat? Quamquam haec quidem praeposita recte et reiecta dicere licebit. At negat Epicurus-hoc enim vestrum lumen estquemquam, qui honeste non vivat, iucunde posse vivere. Eorum enim est haec querela, qui sibi cari sunt seseque diligunt. Haec igitur Epicuri non probo, inquam. Societatem coniunctionis humanae munifice et aeque tuens iustitia dicitur, cui sunt adiunctae pietas, bonitas, liberalitas, benignitas, comitas, quaeque sunt generis eiusdem." +
            "Ergo opifex plus sibi proponet ad formarum quam civis excellens ad factorum pulchritudinem? Maximas vero virtutes iacere omnis necesse est voluptate dominante. Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi; Ille igitur vidit, non modo quot fuissent adhuc philosophorum de summo bono, sed quot omnino esse possent sententiae. Ita multo sanguine profuso in laetitia et in victoria est mortuus. Isto modo, ne si avia quidem eius nata non esset. Sin laboramus, quis est, qui alienae modum statuat industriae? Manebit ergo amicitia tam diu, quam diu sequetur utilitas, et, si utilitas amicitiam constituet, tollet eadem. Est, ut dicis, inquam. Ita enim se Athenis collocavit, ut sit paene unus ex Atticis, ut id etiam cognomen videatur habiturus. Ut etiam contendant et elaborent, si efficere possint, ut aut non appareat corporis vitium aut quam minimum appareat? Ad eas enim res ab Epicuro praecepta dantur." +
            "Erillus autem ad scientiam omnia revocans unum quoddam bonum vidit, sed nec optimum nec quo vita gubernari possit. Voluptatem cum summum bonum diceret, primum in eo ipso parum vidit, deinde hoc quoque alienum; Naturales divitias dixit parabiles esse, quod parvo esset natura contenta. De qua Epicurus quidem ita dicit, omnium rerum, quas ad beate vivendum sapientia comparaverit, nihil esse maius amicitia, nihil uberius, nihil iucundius. Ex quo, id quod omnes expetunt, beate vivendi ratio inveniri et comparari potest. Aufidio, praetorio, erudito homine, oculis capto, saepe audiebam, cum se lucis magis quam utilitatis desiderio moveri diceret. Et si turpitudinem fugimus in statu et motu corporis, quid est cur pulchritudinem non sequamur? Et ille ridens: Age, age, inquit,-satis enim scite me nostri sermonis principium esse voluisti-exponamus adolescenti,. Videsne quam sit magna dissensio? Quid est igitur, cur ita semper deum appellet Epicurus beatum et aeternum?" +
            "Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; Aliter homines, aliter philosophos loqui putas oportere? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Si de re disceptari oportet, nulla mihi tecum, Cato, potest esse dissensio. Poterat autem inpune; Iam doloris medicamenta illa Epicurea tamquam de narthecio proment: Si gravis, brevis; Videmus in quodam volucrium genere non nulla indicia pietatis, cognitionem, memoriam, in multis etiam desideria videmus. Et summatim quidem haec erant de corpore animoque dicenda, quibus quasi informatum est quid hominis natura postulet." +
            "Est autem situm in nobis ut et adversa quasi perpetua oblivione obruamus et secunda iucunde ac suaviter meminerimus. Quodsi, ne quo incommodo afficiare, non relinques amicum, tamen, ne sine fructu alligatus sis, ut moriatur optabis. Sed est forma eius disciplinae, sicut fere ceterarum, triplex: una pars est naturae, disserendi altera, vivendi tertia. Perspicuum est enim, nisi aequitas, fides, iustitia proficiscantur a natura, et si omnia haec ad utilitatem referantur, virum bonum non posse reperiri; Ita ne hoc quidem modo paria peccata sunt." +
            "Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Aliam vero vim voluptatis esse, aliam nihil dolendi, nisi valde pertinax fueris, concedas necesse est. Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Quo plebiscito decreta a senatu est consuli quaestio Cn. Comprehensum, quod cognitum non habet? In eo autem voluptas omnium Latine loquentium more ponitur, cum percipitur ea, quae sensum aliquem moveat, iucunditas. Praeterea sublata cognitione et scientia tollitur omnis ratio et vitae degendae et rerum gerendarum. Servari enim iustitia nisi a forti viro, nisi a sapiente non potest. Sed finge non solum callidum eum, qui aliquid improbe faciat, verum etiam praepotentem, ut M. Ita fit illa conclusio non solum vera, sed ita perspicua, ut dialectici ne rationem quidem reddi putent oportere: si illud, hoc; Ad quorum et cognitionem et usum iam corroborati natura ipsa praeeunte deducimur. Vidit Homerus probari fabulam non posse, si cantiunculis tantus irretitus vir teneretur;" +
            "Est tamen ea secundum naturam multoque nos ad se expetendam magis hortatur quam superiora omnia. In voluptate corporis-addam, si vis, animi, dum ea ipsa, ut vultis, sit e corpore-situm est vivere beate. Tertium autem omnibus aut maximis rebus iis, quae secundum naturam sint, fruentem vivere. Totum autem id externum est, et quod externum, id in casu est. Quae cum magnifice primo dici viderentur, considerata minus probabantur. Quae cum dixisset paulumque institisset, Quid est? Ut Phidias potest a primo instituere signum idque perficere, potest ab alio inchoatum accipere et absolvere, huic est sapientia similis; In contemplatione et cognitione posita rerum, quae quia deorum erat vitae simillima, sapiente visa est dignissima." +
            "Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse. Tanti autem aderant vesicae et torminum morbi, ut nihil ad eorum magnitudinem posset accedere. An haec ab eo non dicuntur? Vitiosum est enim in dividendo partem in genere numerare. Cenasti in vita numquam bene, cum omnia in ista Consumis squilla atque acupensere cum decimano. Tu autem negas fortem esse quemquam posse, qui dolorem malum putet." +
            "Et ille ridens: Age, age, inquit,-satis enim scite me nostri sermonis principium esse voluisti-exponamus adolescenti,. Illa videamus, quae a te de amicitia dicta sunt. Id enim volumus, id contendimus, ut officii fructus sit ipsum officium. Pungunt quasi aculeis interrogatiunculis angustis, quibus etiam qui assentiuntur nihil commutantur animo et idem abeunt, qui venerant. Ad corpus diceres pertinere-, sed ea, quae dixi, ad corpusne refers? Magni enim aestimabat pecuniam non modo non contra leges, sed etiam legibus partam. Praeterea et appetendi et refugiendi et omnino rerum gerendarum initia proficiscuntur aut a voluptate aut a dolore." +
            "Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Ut non sine causa ex iis memoriae ducta sit disciplina. Quis animo aequo videt eum, quem inpure ac flagitiose putet vivere? An obliviscimur, quantopere in audiendo in legendoque moveamur, cum pie, cum amice, cum magno animo aliquid factum cognoscimus? Quam multa vitiosa! summum enim bonum et malum vagiens puer utra voluptate diiudicabit, stante an movente? Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia; Quis, quaeso, illum negat et bonum virum et comem et humanum fuisse? Audio equidem philosophi vocem, Epicure, sed quid tibi dicendum sit oblitus es. Bona autem corporis huic sunt, quod posterius posui, similiora. Solum praeterea formosum, solum liberum, solum civem, stultost;" +
            "Et si turpitudinem fugimus in statu et motu corporis, quid est cur pulchritudinem non sequamur? Qui si ea, quae dicit, ita sentiret, ut verba significant, quid inter eum et vel Pyrrhonem vel Aristonem interesset? Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Mihi quidem Antiochum, quem audis, satis belle videris attendere. Ita relinquet duas, de quibus etiam atque etiam consideret. Bonum liberi: misera orbitas. Ut scias me intellegere, primum idem esse dico voluptatem, quod ille don." +
            "Et summatim quidem haec erant de corpore animoque dicenda, quibus quasi informatum est quid hominis natura postulet. Scripsit enim et multis saepe verbis et breviter arteque in eo libro, quem modo nominavi, mortem nihil ad nos pertinere. Quamquam te quidem video minime esse deterritum. At Zeno eum non beatum modo, sed etiam divitem dicere ausus est. Qualis ista philosophia est, quae non interitum afferat pravitatis, sed sit contenta mediocritate vitiorum? Praetereo multos, in bis doctum hominem et suavem, Hieronymum, quem iam cur Peripateticum appellem nescio. Sit ista in Graecorum levitate perversitas, qui maledictis insectantur eos, a quibus de veritate dissentiunt. Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Quid ergo dubitamus, quin, si non dolere voluptas sit summa, non esse in voluptate dolor sit maximus?" +
            "Et tamen ego a philosopho, si afferat eloquentiam, non asperner, si non habeat, non admodum flagitem. Quod non subducta utilitatis ratione effici solet, sed ipsum a se oritur et sua sponte nascitur. Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse; Aberat omnis dolor, qui si adesset, nec molliter ferret et tamen medicis plus quam philosophis uteretur. Illa autem, morbum, egestatem, dolorem, non appello m a l a, sed, si libet, r e i e c t a n e a." +
            "Ex ea difficultate illae fallaciloquae, ut ait Accius, malitiae natae sunt. Deinde disputat, quod cuiusque generis animantium statui deceat extremum. Praeclare enim Plato: Beatum, cui etiam in senectute contigerit, ut sapientiam verasque opiniones assequi possit. Inde igitur, inquit, ordiendum est. Non enim in selectione virtus ponenda erat, ut id ipsum, quod erat bonorum ultimum, aliud aliquid adquireret. Iam illud quale tandem est, bona praeterita non effluere sapienti, mala meminisse non oportere?" +
            "Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Possumusne ergo in vita summum bonum dicere, cum id ne in cena quidem posse videamur? Semovenda est igitur voluptas, non solum ut recta sequamini, sed etiam ut loqui deceat frugaliter. Quid enim est tam repugnans quam eundem dicere, quod honestum sit, solum id bonum esse, qui dicat appetitionem rerum ad vivendum accommodatarum natura profectam? Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; Comprehensum, quod cognitum non habet?" +
            "Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Quid affers, cur Thorius, cur Caius Postumius, cur omnium horum magister, Orata, non iucundissime vixerit? Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia; Longum est enim ad omnia respondere, quae a te dicta sunt. Quod enim vituperabile est per se ipsum, id eo ipso vitium nominatum puto, vel etiam a vitio dictum vituperari. Quid enim de amicitia statueris utilitatis causa expetenda vides. Easdemne res? Sed tamen enitar et, si minus multa mihi occurrent, non fugiam ista popularia. Quos quidem tibi studiose et diligenter tractandos magnopere censeo." +
            "Ex quo intellegitur idem illud, solum bonum esse, quod honestum sit, idque esse beate vivere: honeste, id est cum virtute, vivere. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Nam si beatus umquam fuisset, beatam vitam usque ad illum a Cyro extructum rogum pertulisset." +
            "Ex quo intellegitur idem illud, solum bonum esse, quod honestum sit, idque esse beate vivere: honeste, id est cum virtute, vivere. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Longum est enim ad omnia respondere, quae a te dicta sunt. Quia, si mala sunt, is, qui erit in iis, beatus non erit. Ut pulsi recurrant? Quamquam id quidem licebit iis existimare, qui legerint. Nec vero ut voluptatem expetat, natura movet infantem, sed tantum ut se ipse diligat, ut integrum se salvumque velit. Sin ea non neglegemus neque tamen ad finem summi boni referemus, non multum ab Erilli levitate aberrabimus. Scio enim esse quosdam, qui quavis lingua philosophari possint; Unum nescio, quo modo possit, si luxuriosus sit, finitas cupiditates habere. Quam multa vitiosa! summum enim bonum et malum vagiens puer utra voluptate diiudicabit, stante an movente? Quid enim est a Chrysippo praetermissum in Stoicis?" +
            "Experiamur igitur, inquit, etsi habet haec Stoicorum ratio difficilius quiddam et obscurius. Heri, inquam, ludis commissis ex urbe profectus veni ad vesperum. Quid enim mihi potest esse optatius quam cum Catone, omnium virtutum auctore, de virtutibus disputare? Quod autem principium officii quaerunt, melius quam Pyrrho; Itaque rursus eadem ratione, qua sum paulo ante usus, haerebitis. Nec vero intermittunt aut admirationem earum rerum, quae sunt ab antiquis repertae, aut investigationem novarum." +
            "Fieri, inquam, Triari, nullo pacto potest, ut non dicas, quid non probes eius, a quo dissentias. Num igitur eum postea censes anxio animo aut sollicito fuisse? Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; An ea, quae per vinitorem antea consequebatur, per se ipsa curabit? Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Urgent tamen et nihil remittunt." +
            "Fortasse id optimum, sed ubi illud: Plus semper voluptatis? Dicet pro me ipsa virtus nec dubitabit isti vestro beato M. Possumusne ergo in vita summum bonum dicere, cum id ne in cena quidem posse videamur? Nihil acciderat ei, quod nollet, nisi quod anulum, quo delectabatur, in mari abiecerat. Ea, quae dialectici nunc tradunt et docent, nonne ab illis instituta sunt aut inventa sunt? Virtutis enim beataeque vitae, quae duo maxime expetenda sunt, serius lumen apparet, multo etiam serius, ut plane qualia sint intellegantur. Cum autem progrediens confirmatur animus, agnoscit ille quidem naturae vim, sed ita, ut progredi possit longius, per se sit tantum inchoata. Ut in geometria, prima si dederis, danda sunt omnia. Ita relinquet duas, de quibus etiam atque etiam consideret. Haec videlicet est correctio philosophiae veteris et emendatio, quae omnino aditum habere nullum potest in urbem, in forum, in curiam. Aufidio, praetorio, erudito homine, oculis capto, saepe audiebam, cum se lucis magis quam utilitatis desiderio moveri diceret. Nam si quae sunt aliae, falsum est omnis animi voluptates esse e corporis societate. Nec vero pietas adversus deos nec quanta iis gratia debeatur sine explicatione naturae intellegi potest. Et quidem, Cato, hanc totam copiam iam Lucullo nostro notam esse oportebit; Ergo opifex plus sibi proponet ad formarum quam civis excellens ad factorum pulchritudinem? Tum ego: Non mehercule, inquam, soleo temere contra Stoicos, non quo illis admodum assentiar, sed pudore impedior;" +
            "Hi autem ponunt illi quidem prima naturae, sed ea seiungunt a finibus et a summa bonorum; Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. At Zeno eum non beatum modo, sed etiam divitem dicere ausus est. Ad corpus diceres pertinere-, sed ea, quae dixi, ad corpusne refers? Sed quamvis comis in amicis tuendis fuerit, tamen, si haec vera sunt-nihil enim affirmo-, non satis acutus fuit. Sit enim idem caecus, debilis. Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Sunt autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos diligant. Conclusum est enim contra Cyrenaicos satis acute, nihil ad Epicurum. Te autem hortamur omnes, currentem quidem, ut spero, ut eos, quos novisse vis, imitari etiam velis. Zenonis est, inquam, hoc Stoici. Aut pertinacissimus fueris, si in eo perstiteris ad corpus ea, quae dixi, referri, aut deserueris totam Epicuri voluptatem, si negaveris. Illa videamus, quae a te de amicitia dicta sunt." +
            "Hi autem ponunt illi quidem prima naturae, sed ea seiungunt a finibus et a summa bonorum; Quocumque enim modo summum bonum sic exponitur, ut id vacet honestate, nec officia nec virtutes in ea ratione nec amicitiae constare possunt. Quae si potest singula consolando levare, universa quo modo sustinebit? Equidem etiam Epicurum, in physicis quidem, Democriteum puto. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia; Sed cum, quod honestum sit, id solum bonum esse dicamus, consentaneum tamen est fungi officio, cum id officium nec in bonis ponamus nec in malis. Stulti autem malorum memoria torquentur, sapientes bona praeterita grata recordatione renovata delectant. Quid, si reviviscant Platonis illi et deinceps qui eorum auditores fuerunt, et tecum ita loquantur? Sin laboramus, quis est, qui alienae modum statuat industriae? Esse enim quam vellet iniquus iustus poterat inpune. Verum hoc idem saepe faciamus." +
            "Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Nec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus. In voluptate corporis-addam, si vis, animi, dum ea ipsa, ut vultis, sit e corpore-situm est vivere beate. Vives, inquit Aristo, magnifice atque praeclare, quod erit cumque visum ages, numquam angere, numquam cupies, numquam timebis. Nec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus. Itaque haec cum illis est dissensio, cum Peripateticis nulla sane. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Sed et illum, quem nominavi, et ceteros sophistas, ut e Platone intellegi potest, lusos videmus a Socrate. Tertium autem omnibus aut maximis rebus iis, quae secundum naturam sint, fruentem vivere." +
            "Hoc est non modo cor non habere, sed ne palatum quidem. Illa enim, quae prosunt aut quae nocent, aut bona sunt aut mala, quae sint paria necesse est. Sine ea igitur iucunde negat posse se vivere? Quem quidem vos, cum improbis poenam proponitis, inpetibilem facitis, cum sapientem semper boni plus habere vultis, tolerabilem. Nam de isto magna dissensio est. Sine ea igitur iucunde negat posse se vivere? Quare si potest esse beatus is, qui est in asperis reiciendisque rebus, potest is quoque esse. Quare aliud aliquod, Torquate, hominis summum bonum reperiendum est, voluptatem bestiis concedamus, quibus vos de summo bono testibus uti soletis." +
            "Hoc uno captus Erillus scientiam summum bonum esse defendit nec rem ullam aliam per se expetendam. Quasi vero, inquit, perpetua oratio rhetorum solum, non etiam philosophorum sit. Quod praeceptum quia maius erat, quam ut ab homine videretur, idcirco assignatum est deo. Respondebo me non quaerere, inquam, hoc tempore quid virtus efficere possit, sed quid constanter dicatur, quid ipsum a se dissentiat. His singulis copiose responderi solet, sed quae perspicua sunt longa esse non debent. Mihi autem nihil tam perspicuum videtur, quam has sententias eorum philosophorum re inter se magis quam verbis dissidere; Nam si +omnino nos+ neglegemus, in Aristonea vitia incidemus et peccata obliviscemurque quae virtuti ipsi principia dederimus; Quae hic rei publicae vulnera inponebat, eadem ille sanabat. Ex quo intellegitur officium medium quiddam esse, quod neque in bonis ponatur neque in contrariis. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Aliis esse maiora, illud dubium, ad id, quod summum bonum dicitis, ecquaenam possit fieri accessio. Hi autem ponunt illi quidem prima naturae, sed ea seiungunt a finibus et a summa bonorum;" +
            "Huic verbo omnes, qui ubique sunt, qui Latine sciunt, duas res subiciunt, laetitiam in animo, commotionem suavem iucunditatis in corpore. Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. Consequatur summas voluptates non modo parvo, sed per me nihilo, si potest; Amicitiae vero locus ubi esse potest aut quis amicus esse cuiquam, quem non ipsum amet propter ipsum? Quod si ita se habeat, non possit beatam praestare vitam sapientia. Quasi vero, inquit, perpetua oratio rhetorum solum, non etiam philosophorum sit. Ipse negat, ut ante dixi, luxuriosorum vitam reprehendendam, nisi plane fatui sint, id est nisi aut cupiant aut metuant. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant." +
            "In motu et in statu corporis nihil inest, quod animadvertendum esse ipsa natura iudicet? Nonne odio multos dignos putamus, qui quodam motu aut statu videntur naturae legem et modum contempsisse? Ut optime, secundum naturam affectum esse possit. In contemplatione et cognitione posita rerum, quae quia deorum erat vitae simillima, sapiente visa est dignissima. Non modo carum sibi quemque, verum etiam vehementer carum esse? Prioris generis est docilitas, memoria;" +
            "In parvis enim saepe, qui nihil eorum cogitant, si quando iis ludentes minamur praecipitaturos alicunde, extimescunt. Quin etiam ferae, inquit Pacuvius, quíbus abest, ad praécavendum intéllegendi astútia, iniecto terrore mortis horrescunt. Perspicuum est enim, nisi aequitas, fides, iustitia proficiscantur a natura, et si omnia haec ad utilitatem referantur, virum bonum non posse reperiri; Numquam hoc ita defendit Epicurus neque Metrodorus aut quisquam eorum, qui aut saperet aliquid aut ista didicisset. De quibus etsi a Chrysippo maxime est elaboratum, tamen a Zenone minus multo quam ab antiquis; Sed quoniam et advesperascit et mihi ad villam revertendum est, nunc quidem hactenus; Si ad corpus pertinentibus, rationes tuas te video compensare cum istis doloribus, non memoriam corpore perceptarum voluptatum;" +
            "In qua si nihil est praeter rationem, sit in una virtute finis bonorum; Ita fit ut, quanta differentia est in principiis naturalibus, tanta sit in finibus bonorum malorumque dissimilitudo. Nec lapathi suavitatem acupenseri Galloni Laelius anteponebat, sed suavitatem ipsam neglegebat; Aeque enim contingit omnibus fidibus, ut incontentae sint. Diodorus, eius auditor, adiungit ad honestatem vacuitatem doloris. Quae quidem sapientes sequuntur duce natura tamquam videntes; Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus; Gerendus est mos, modo recte sentiat." +
            "In schola desinis. Itaque haec cum illis est dissensio, cum Peripateticis nulla sane. Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Ea enim omnia, quae illi bona dicerent, praeposita esse, non bona, itemque illa, quae in corpore excellerent, stulte antiquos dixisse per se esse expetenda; Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. In qua si nihil est praeter rationem, sit in una virtute finis bonorum; Videmus in quodam volucrium genere non nulla indicia pietatis, cognitionem, memoriam, in multis etiam desideria videmus. Sed finge non solum callidum eum, qui aliquid improbe faciat, verum etiam praepotentem, ut M. Ab his oratores, ab his imperatores ac rerum publicarum principes extiterunt. Illud mihi a te nimium festinanter dictum videtur, sapientis omnis esse semper beatos;" +
            "Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; Sed est forma eius disciplinae, sicut fere ceterarum, triplex: una pars est naturae, disserendi altera, vivendi tertia. Quod si ita sit, cur opera philosophiae sit danda nescio. Teneo, inquit, finem illi videri nihil dolere. Quae rursus dum sibi evelli ex ordine nolunt, horridiores evadunt, asperiores, duriores et oratione et moribus. Itaque ne iustitiam quidem recte quis dixerit per se ipsam optabilem, sed quia iucunditatis vel plurimum afferat. Et hi quidem ita non sola virtute finem bonorum contineri putant, ut rebus tamen omnibus virtutem anteponant; Negare non possum. Atque ut a corpore ordiar, videsne ut, si quae in membris prava aut debilitata aut inminuta sint, occultent homines? Hoc loco tenere se Triarius non potuit. Quod enim vituperabile est per se ipsum, id eo ipso vitium nominatum puto, vel etiam a vitio dictum vituperari. Quare attende, quaeso. Non igitur de improbo, sed de callido improbo quaerimus, qualis Q." +
            "Intrandum est igitur in rerum naturam et penitus quid ea postulet pervidendum; Quos nisi redarguimus, omnis virtus, omne decus, omnis vera laus deserenda est. Nec vero audiendus Hieronymus, cui summum bonum est idem, quod vos interdum vel potius nimium saepe dicitis, nihil dolere. Perfecto enim et concluso neque virtutibus neque amicitiis usquam locum esse, si ad voluptatem omnia referantur, nihil praeterea est magnopere dicendum. Iam insipientes alios ita esse, ut nullo modo ad sapientiam possent pervenire, alios, qui possent, si id egissent, sapientiam consequi. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret. Vives, inquit Aristo, magnifice atque praeclare, quod erit cumque visum ages, numquam angere, numquam cupies, numquam timebis. Honestum igitur id intellegimus, quod tale est, ut detracta omni utilitate sine ullis praemiis fructibusve per se ipsum possit iure laudari. Sed quamvis comis in amicis tuendis fuerit, tamen, si haec vera sunt-nihil enim affirmo-, non satis acutus fuit. Quae dici eadem de ceteris virtutibus possunt, quarum omnium fundamenta vos in voluptate tamquam in aqua ponitis. De ingenio eius in his disputationibus, non de moribus quaeritur. Quae cum dixisset, finem ille." +
            "Hunc igitur finem illi tenuerunt, quodque ego pluribus verbis, illi brevius secundum naturam vivere, hoc iis bonorum videbatur extremum. Atque hoc loco similitudines eas, quibus illi uti solent, dissimillimas proferebas. Nam si quae sunt aliae, falsum est omnis animi voluptates esse e corporis societate. In eo autem voluptas omnium Latine loquentium more ponitur, cum percipitur ea, quae sensum aliquem moveat, iucunditas. Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter. Et si turpitudinem fugimus in statu et motu corporis, quid est cur pulchritudinem non sequamur?" +
            "Hunc igitur finem illi tenuerunt, quodque ego pluribus verbis, illi brevius secundum naturam vivere, hoc iis bonorum videbatur extremum. Sed existimo te, sicut nostrum Triarium, minus ab eo delectari, quod ista Platonis, Aristoteli, Theophrasti orationis ornamenta neglexerit. Princeps huius civitatis Phalereus Demetrius cum patria pulsus esset iniuria, ad Ptolomaeum se regem Alexandream contulit. Quae in controversiam veniunt, de iis, si placet, disseramus. Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi; Immo istud quidem, inquam, quo loco quidque, nisi iniquum postulo, arbitratu meo. An dubium est, quin virtus ita maximam partem optineat in rebus humanis, ut reliquas obruat? Amicitiae vero locus ubi esse potest aut quis amicus esse cuiquam, quem non ipsum amet propter ipsum? Nam e quibus locis quasi thesauris argumenta depromerentur, vestri ne suspicati quidem sunt, superiores autem artificio et via tradiderunt. Atque ego: Scis me, inquam, istud idem sentire, Piso, sed a te opportune facta mentio est. Societatem coniunctionis humanae munifice et aeque tuens iustitia dicitur, cui sunt adiunctae pietas, bonitas, liberalitas, benignitas, comitas, quaeque sunt generis eiusdem. Etenim si delectamur, cum scribimus, quis est tam invidus, qui ab eo nos abducat? Omnibus enim artibus volumus attributam esse eam, quae communis appellatur prudentia, quam omnes, qui cuique artificio praesunt, debent habere. Illum mallem levares, quo optimum atque humanissimum virum, Cn. Hoc est non modo cor non habere, sed ne palatum quidem." +
            "Hunc ipsum Zenonis aiunt esse finem declarantem illud, quod a te dictum est, convenienter naturae vivere. Et ais, si una littera commota sit, fore tota ut labet disciplina. Quare aliud aliquod, Torquate, hominis summum bonum reperiendum est, voluptatem bestiis concedamus, quibus vos de summo bono testibus uti soletis. Nam quibus rebus efficiuntur voluptates, eae non sunt in potestate sapientis. Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse;" +
            "Iam insipientes alios ita esse, ut nullo modo ad sapientiam possent pervenire, alios, qui possent, si id egissent, sapientiam consequi. Itaque in rebus minime obscuris non multus est apud eos disserendi labor. Sin ea non neglegemus neque tamen ad finem summi boni referemus, non multum ab Erilli levitate aberrabimus. Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. Atque hoc loco similitudines eas, quibus illi uti solent, dissimillimas proferebas. Hoc non est positum in nostra actione. Perfecto enim et concluso neque virtutibus neque amicitiis usquam locum esse, si ad voluptatem omnia referantur, nihil praeterea est magnopere dicendum." +
            "Ille vero, si insipiens-quo certe, quoniam tyrannus -, numquam beatus; Ita similis erit ei finis boni, atque antea fuerat, neque idem tamen; Sed hoc summum bonum, quod tertia significatione intellegitur, eaque vita, quae ex summo bono degitur, quia coniuncta ei virtus est. Modo etiam paulum ad dexteram de via declinavi, ut ad Pericli sepulcrum accederem. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Si est nihil nisi corpus, summa erunt illa: valitudo, vacuitas doloris, pulchritudo, cetera. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam." +
            "Ille vero, si insipiens-quo certe, quoniam tyrannus -, numquam beatus; Si mala non sunt, iacet omnis ratio Peripateticorum. Quae qui non vident, nihil umquam magnum ac cognitione dignum amaverunt. Quo modo igitur, inquies, verum esse poterit omnia referri ad summum bonum, si amicítiae, si propinquitates, si reliqua externa summo bono non continentur? Hoc est vim afferre, Torquate, sensibus, extorquere ex animis cognitiones verborum, quibus inbuti sumus. Quod maxime efficit Theophrasti de beata vita liber, in quo multum admodum fortunae datur. Nam si +omnino nos+ neglegemus, in Aristonea vitia incidemus et peccata obliviscemurque quae virtuti ipsi principia dederimus; An quod ita callida est, ut optime possit architectari voluptates? De malis autem et bonis ab iis animalibus, quae nondum depravata sint, ait optime iudicari. At modo dixeras nihil in istis rebus esse, quod interesset. Ipse negat, ut ante dixi, luxuriosorum vitam reprehendendam, nisi plane fatui sint, id est nisi aut cupiant aut metuant. Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta?" +
            "Illis videtur, qui illud non dubitant bonum dicere -; Nam, ut paulo ante docui, augendae voluptatis finis est doloris omnis amotio. Quae fere omnia appellantur uno ingenii nomine, easque virtutes qui habent, ingeniosi vocantur. In primo enim ortu inest teneritas ac mollitia quaedam, ut nec res videre optimas nec agere possint." +
            "In motu et in statu corporis nihil inest, quod animadvertendum esse ipsa natura iudicet? Mihi vero, inquit, placet agi subtilius et, ut ipse dixisti, pressius. Cur iustitia laudatur? Conferam tecum, quam cuique verso rem subicias; Negat enim summo bono afferre incrementum diem. Quod dicit Epicurus etiam de voluptate, quae minime sint voluptates, eas obscurari saepe et obrui. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Quia, cum a Zenone, inquam, hoc magnifice tamquam ex oraculo editur: Virtus ad beate vivendum se ipsa contenta est, et Quare? Quam multa vitiosa! summum enim bonum et malum vagiens puer utra voluptate diiudicabit, stante an movente? Ergo illi intellegunt quid Epicurus dicat, ego non intellego? Sed erat aequius Triarium aliquid de dissensione nostra iudicare. Restinguet citius, si ardentem acceperit. Honestum igitur id intellegimus, quod tale est, ut detracta omni utilitate sine ullis praemiis fructibusve per se ipsum possit iure laudari." +
            "Istam voluptatem perpetuam quis potest praestare sapienti? Omnibus enim artibus volumus attributam esse eam, quae communis appellatur prudentia, quam omnes, qui cuique artificio praesunt, debent habere. Et quidem illud ipsum non nimium probo et tantum patior, philosophum loqui de cupiditatibus finiendis. Pompeius in foedere Numantino infitiando fuit, nec vero omnia timente, sed primum qui animi conscientiam non curet, quam scilicet comprimere nihil est negotii. Societatem coniunctionis humanae munifice et aeque tuens iustitia dicitur, cui sunt adiunctae pietas, bonitas, liberalitas, benignitas, comitas, quaeque sunt generis eiusdem. Qua exposita scire cupio quae causa sit, cur Zeno ab hac antiqua constitutione desciverit, quidnam horum ab eo non sit probatum; Quodsi ipsam honestatem undique pertectam atque absolutam." +
            "Ita enim vivunt quidam, ut eorum vita refellatur oratio. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. Utrum igitur tibi non placet, inquit, virtutisne tantam esse vim, ut ad beate vivendum se ipsa contenta sit? Reperiam multos, vel innumerabilis potius, non tam curiosos nec tam molestos, quam vos estis, quibus, quid velim, facile persuadeam. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Atque hoc dabitis, ut opinor, si modo sit aliquid esse beatum, id oportere totum poni in potestate sapientis. Quod si ita est, sequitur id ipsum, quod te velle video, omnes semper beatos esse sapientes." +
            "Ita multo sanguine profuso in laetitia et in victoria est mortuus. Praeclare enim Plato: Beatum, cui etiam in senectute contigerit, ut sapientiam verasque opiniones assequi possit. Nec hoc ille non vidit, sed verborum magnificentia est et gloria delectatus. Ita finis bonorum existit secundum naturam vivere sic affectum, ut optime is affici possit ad naturamque accommodatissime." +
            "Ita relinquet duas, de quibus etiam atque etiam consideret. Ut proverbia non nulla veriora sint quam vestra dogmata. Quodsi Graeci leguntur a Graecis isdem de rebus alia ratione compositis, quid est, cur nostri a nostris non legantur? Hoc enim constituto in philosophia constituta sunt omnia. Tertium autem omnibus aut maximis rebus iis, quae secundum naturam sint, fruentem vivere. Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest. Sit hoc ultimum bonorum, quod nunc a me defenditur; Nam diligi et carum esse iucundum est propterea, quia tutiorem vitam et voluptatem pleniorem efficit. Et certamen honestum et disputatio splendida! omnis est enim de virtutis dignitate contentio. Quem enim ardorem studii censetis fuisse in Archimede, qui dum in pulvere quaedam describit attentius, ne patriam quidem captam esse senserit?" +
            "Itaque a sapientia praecipitur se ipsam, si usus sit, sapiens ut relinquat. Verba tu fingas et ea dicas, quae non sentias? Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Quo modo autem optimum, si bonum praeterea nullum est? Sic igitur in homine perfectio ista in eo potissimum, quod est optimum, id est in virtute, laudatur. Hoc loco tenere se Triarius non potuit. Quoniam, si dis placet, ab Epicuro loqui discimus. In qua quid est boni praeter summam voluptatem, et eam sempiternam?" +
            "Itaque his sapiens semper vacabit. Scisse enim te quis coarguere possit? Is enim percontando atque interrogando elicere solebat eorum opiniones, quibuscum disserebat, ut ad ea, quae ii respondissent, si quid videretur, diceret. Summum a vobis bonum voluptas dicitur. Hunc ipsum Zenonis aiunt esse finem declarantem illud, quod a te dictum est, convenienter naturae vivere. Negat enim summo bono afferre incrementum diem.";

    private final HuffmanCompressor huffmanCompressor = new HuffmanCompressor(
            new SymbolWeightMapBuilder(),
            new HuffmanTreeBuilder(),
            new HuffmanTreeSerializer()
    );

    private final HuffmanDecompressor huffmanDecompressor = new HuffmanDecompressor(
            new HuffmanTreeDeserializer()
    );

    private final ByteArrayOutputStream compressedStream = new ByteArrayOutputStream();

    @Test
    void shouldCompressAndDecompress() throws IOException {
        whenCompressingData();
        thenDataIsCompressed();
        thenCompressedDataShouldBeCorrectlyDecompressed();
        thenTheCompressionRatioIsPrintedOut();
    }

    private void thenTheCompressionRatioIsPrintedOut() {
        long inputSize = TEST_DATA.getBytes().length;
        System.out.printf("Input size: %d - Compressed size: %d - Compression ratio: %5.2f%%%n",
                inputSize,
                compressedStream.size(),
                (inputSize-compressedStream.size())*100.0/inputSize);
    }

    private void thenDataIsCompressed() {
        assertThat(compressedStream.toByteArray()).hasSizeLessThan(TEST_DATA.getBytes().length);
    }

    private void thenCompressedDataShouldBeCorrectlyDecompressed() throws IOException {
        ByteArrayOutputStream decompressedStream = new ByteArrayOutputStream();
        huffmanDecompressor.decompress(new ByteArrayInputStream(compressedStream.toByteArray()), decompressedStream);
        assertThat(decompressedStream.toByteArray()).isEqualTo(TEST_DATA.getBytes());
    }

    private void whenCompressingData() throws IOException {
        huffmanCompressor.compress(new ByteArrayInputStream(TEST_DATA.getBytes()), compressedStream, true);
    }
}
